(in-package :chron-r2-0-c)

(defun %c-assert (condition description)
  (unless condition (error "R2.0-C verification failed: ~A" description)) t)

(defun %c-fixture ()
  (let* ((store (make-memory-store)) (graph (make-causal-graph))
         (root (make-causal-node "root" :system (store-payload store "root")))
         (head (make-causal-node "head" :prompt (store-payload store "head")))
         (registry (make-world-registry :graph graph :memory store)))
    (add-node! graph root) (add-node! graph head)
    (add-edge! graph (make-causal-edge "root" "head" :causal))
    (values graph store registry)))

(defun d1-world-non-mutation ()
  (multiple-value-bind (graph store registry) (%c-fixture)
    (declare (ignore registry))
    (let* ((world (make-world "world" graph store "root" "head"
                              '(:include-evaluations nil) '(:label "stable")))
           (before (list (world-id world) (world-root-node world) (world-head-node world)
                         (world-projection-policy world) (world-metadata world)
                         (world-lifecycle world)))
           (observation (describe-world world)))
      (%c-assert (world-observation-p observation) "describe-world must return a world observation")
      (%c-assert (equal before (list (world-id world) (world-root-node world) (world-head-node world)
                                     (world-projection-policy world) (world-metadata world)
                                     (world-lifecycle world)))
                 "describing a world must not modify it")
      (%c-assert (equal (world-observation-schema-version observation) +observation-schema-version+)
                 "world observations expose schema version") t)))

(defun d2-registry-non-mutation ()
  (multiple-value-bind (graph store registry) (%c-fixture)
    (let* ((first (make-world "first" graph store "root" "head" nil))
           (second (make-world "second" graph store "root" "head" nil)))
      (register-world registry first)
      (register-world registry second)
      (set-active-world registry "second")
      (archive-world registry "first")
      (let* ((before (list (list-worlds registry) (active-world registry) (chron-r2-0-a::world-registry-ancestry registry)))
             (observation (describe-registry registry))
             (after (list (list-worlds registry) (active-world registry) (chron-r2-0-a::world-registry-ancestry registry))))
        (%c-assert (registry-observation-p observation) "describe-registry must return a registry observation")
        (%c-assert (equal before after) "describing a registry must not mutate it") t))))

(defun d3-deterministic-observation ()
  (multiple-value-bind (graph store registry) (%c-fixture)
    (let* ((world (make-world "world" graph store "root" "head" nil))
           (left (describe-world world))
           (right (describe-world world))
           (left-registry (describe-registry registry))
           (right-registry (describe-registry registry)))
      (%c-assert (equal (world-observation-world-id left) (world-observation-world-id right))
                 "world observations are deterministic")
      (%c-assert (equal (registry-observation-world-ids left-registry) (registry-observation-world-ids right-registry))
                 "registry observations are deterministic") t)))

(defun d4-accurate-ancestry ()
  (multiple-value-bind (graph store registry) (%c-fixture)
    (let* ((parent (make-world "parent" graph store "root" "head" nil))
           (child (make-world "child" graph store "root" "head" nil)))
      (register-world registry parent)
      (register-world registry child :parent-id "parent")
      (let ((observation (describe-ancestry registry "child")))
        (%c-assert (ancestry-observation-p observation) "describe-ancestry must return an ancestry observation")
        (%c-assert (equal (ancestry-observation-world-id observation) "child")
                   "ancestry observation reports the child world id")
        (%c-assert (equal (ancestry-observation-parent-world-id observation) "parent")
                   "ancestry observation reports the parent world id")
        (%c-assert (equal (ancestry-observation-ancestry-path observation) '("child" . "parent"))
                   "ancestry observation reports the runtime ancestry edge") t))))

(defun d5-deterministic-difference ()
  (multiple-value-bind (graph store registry) (%c-fixture)
    (let* ((world (make-world "world" graph store "root" "head" nil))
           (left (describe-world world))
           (right (describe-world world))
           (other (describe-registry registry))
           (diff-one (describe-diff left right))
           (diff-two (describe-diff left right))
           (diff-three (describe-diff left other)))
      (%c-assert (diff-observation-p diff-one) "describe-diff must return a diff observation")
      (%c-assert (equal (diff-observation-changed-p diff-one) nil)
                 "identical observations produce no difference")
      (%c-assert (equal (diff-observation-changed-fields diff-one) nil)
                 "identical observations produce no changed fields")
      (%c-assert (equal (diff-observation-changed-p diff-two) nil)
                 "repeated diff observation remains deterministic")
      (%c-assert (equal (diff-observation-changed-p diff-three) t)
                 "different observation kinds are detected") t)))

(defun d6-representation-independence ()
  (multiple-value-bind (graph store registry) (%c-fixture)
    (declare (ignore registry))
    (let* ((world-a (make-world "same" graph store "root" "head" nil))
           (world-b (make-world "same" graph store "root" "head" nil))
           (observation-a (describe-world world-a))
           (observation-b (describe-world world-b)))
      (%c-assert (equal (world-observation-world-id observation-a) (world-observation-world-id observation-b))
                 "equivalent worlds produce equivalent observations")
      (%c-assert (equal (world-observation-root-node-id observation-a) (world-observation-root-node-id observation-b))
                 "observation semantics remain representation independent") t)))

(defun d7-value-object-equality ()
  (multiple-value-bind (graph store registry) (%c-fixture)
    (declare (ignore registry))
    (let* ((world-a (make-world "same" graph store "root" "head" nil))
           (world-b (make-world "same" graph store "root" "head" nil))
           (observation-a (describe-world world-a))
           (observation-b (describe-world world-b)))
      (%c-assert (or (equal observation-a observation-b)
                     (and (funcall #'chron-r2-0-c::world-observation-equal observation-a observation-b)
                          (funcall #'chron-r2-0-c::world-observation-equal observation-b observation-a)))
                 "observation objects compare by content") t)))

(defun run-r2-0-c-tests ()
  (dolist (test '(d1-world-non-mutation d2-registry-non-mutation d3-deterministic-observation
                  d4-accurate-ancestry d5-deterministic-difference d6-representation-independence
                  d7-value-object-equality) t)
    (%c-assert (funcall test) test)))
