(in-package :chron-r2-0-a)

(defun %assert (condition description)
  (unless condition (error "R2.0-A invariant failed: ~A" description)) t)

(defun %fixture (&key (with-evaluation t))
  (let* ((store (make-memory-store)) (graph (make-causal-graph))
         (system (make-causal-node "s" :system (store-payload store "System fact")))
         (prompt (make-causal-node "p" :prompt (store-payload store "User fact")))
         (evaluation (make-causal-node "e" :eval (store-payload store "Helpful"))))
    (add-node! graph system) (add-node! graph prompt)
    (add-edge! graph (make-causal-edge "s" "p" :causal))
    (when with-evaluation
      (add-node! graph evaluation) (add-edge! graph (make-causal-edge "p" "e" :eval)))
    (values graph store)))

(defun t1-memory-determinism ()
  (let* ((store (make-memory-store)) (one (store-payload store "immutable"))
         (two (store-payload store "immutable")))
    (%assert (string= (payload-ref-hash one) (payload-ref-hash two)) "same content must have same hash")
    (%assert (string= "immutable" (load-payload store one)) "stored payload must remain unchanged") t))
(defun t2-graph-replay ()
  (multiple-value-bind (graph store) (%fixture) (declare (ignore store))
    (%assert (equal (mapcar #'causal-node-id (causal-subgraph graph "p")) '("s" "p")) "causal order")
    (%assert (equal (causal-subgraph graph "p") (causal-subgraph graph "p")) "replay repeatability") t))
(defun t3-view-separation ()
  (multiple-value-bind (graph store) (%fixture) (declare (ignore store))
    (%assert (not (find "e" (causal-subgraph graph "p") :key #'causal-node-id :test #'equal)) "eval must not enter causal view") t))
(defun t4-context-projection ()
  (multiple-value-bind (graph store) (%fixture)
    (let ((context (project-context graph store "p" :include-evaluations t)))
      (%assert (equal (mapcar #'context-node-content context) '("System fact" "User fact")) "causal content")
      (%assert (equal (context-node-feedbacks (second context)) '("Helpful")) "evaluation content") t)))
(defun t5-prefill-hash-stability ()
  (multiple-value-bind (graph store) (%fixture)
    (%assert (string= (prefill-state-hash (build-prefill-state graph store "p" :include-evaluations t))
                       (prefill-state-hash (build-prefill-state graph store "p" :include-evaluations t))) "identical inputs hash identically") t))
(defun t6-evaluation-independence ()
  (multiple-value-bind (with-eval store-a) (%fixture :with-evaluation t)
    (multiple-value-bind (without-eval store-b) (%fixture :with-evaluation nil)
      (%assert (string= (prefill-state-hash (build-prefill-state with-eval store-a "p"))
                         (prefill-state-hash (build-prefill-state without-eval store-b "p"))) "eval-free policy must ignore eval nodes") t)))

(defun run-r2-0-a-tests ()
  (dolist (test '(t1-memory-determinism t2-graph-replay t3-view-separation
                  t4-context-projection t5-prefill-hash-stability t6-evaluation-independence)
           t)
    (%assert (funcall test) test)))
