(in-package :chronos-r1)

;;;; R1 reference runtime.  Canonical is persistent: COMMIT constructs a new
;;;; value, so rejected/deferred candidates cannot partially change history.

(defparameter +sources+ '(:user :assistant :tool :system))
(defparameter +intents+ '(:append :reflect :tool :memory-read :memory-write :recover :summarize))
(defparameter +actions+ '(:accept :reject :defer :retry :retry-penalty :abort))

(defstruct (event (:constructor make-event (id source payload &optional metadata)))
  (id 0 :type integer :read-only t) (source :system :read-only t)
  (payload "" :read-only t) (metadata nil :type list :read-only t))
(defstruct (candidate (:constructor make-candidate
                         (id source trigger intent payload &optional constraints metadata)))
  (id 0 :type integer :read-only t) (source :assistant :read-only t)
  trigger (intent :append :read-only t) payload
  (constraints nil :type list :read-only t) (metadata nil :type list :read-only t))
(defstruct (canonical (:constructor make-canonical (&key (history nil) (config nil)
                                                          (memory-ref nil) (clock 0))))
  (history nil :type list :read-only t) (config nil :type list :read-only t)
  (memory-ref nil :type list :read-only t) (clock 0 :type integer :read-only t))
(defstruct (validation-report (:constructor %make-validation-report))
  candidate-id syntax-violations semantic-violations invariant-violations observations)
(defstruct (runtime-command (:constructor make-runtime-command (kind &optional data)))
  kind data)
(defstruct (kernel-state (:constructor make-kernel-state (&key canonical deferred-queue working faults)))
  canonical (deferred-queue nil) working (faults nil))
(defstruct (runtime (:constructor make-runtime (&key state (next-candidate-id 1) last-command)))
  state (next-candidate-id 1) last-command)

(defun plist-copy (value) (copy-tree value))
(defun event->projection (event)
  (list :id (event-id event) :source (event-source event) :payload (event-payload event)
        :metadata (plist-copy (event-metadata event))))
(defun last-event (canonical) (car (last (canonical-history canonical))))
(defun next-event-id (canonical) (1+ (length (canonical-history canonical))))

;;; Derived data: no structures returned here alias Canonical's list/plists.
(defun derive (canonical)
  (let* ((projection (mapcar #'event->projection (canonical-history canonical)))
         (graph (loop for event in (canonical-history canonical)
                      for previous = nil then event
                      collect (list :id (event-id event)
                                    :parent (or (getf (event-metadata event) :causal-parent)
                                                (and previous (event-id previous)))
                                    :causal-id (getf (event-metadata event) :causal-id))))
         (limit (or (getf (canonical-config canonical) :summary-limit) 8))
         (recent (last projection limit))
         (summary (with-output-to-string (out)
                    (dolist (item recent)
                      (format out "~(~A~): ~A~%" (getf item :source) (getf item :payload))))))
    (list :projection projection :graph graph :summary summary)))
(defun replay (canonical) (derive canonical))

(defun build-prompt (derived memory-ref config)
  "Deterministic prompt builder.  Its inputs deliberately exclude observations/faults/metrics."
  (with-output-to-string (out)
    (format out "<|begin_of_text|>~%")
    (format out "<|start_header_id|>system<|end_header_id|>~%~A~%"
            (or (getf config :system-prompt) "You are a helpful assistant."))
    (format out "<|start_header_id|>summary<|end_header_id|>~%~A"
            (getf derived :summary))
    (format out "<|start_header_id|>memory<|end_header_id|>~%~S~%" memory-ref)
    (format out "<|start_header_id|>assistant<|end_header_id|>")))

(defun violation (code reason) (list :code code :reason reason))
(defun invariant (category code recoverable)
  (list :category category :code code :recoverable recoverable))
(defun observation (detector score threshold recommendation)
  (list :detector detector :score score :threshold threshold :recommendation recommendation))
(defun candidate-syntax-violations (candidate)
  (append (unless (and (integerp (candidate-id candidate)) (plusp (candidate-id candidate)))
            (list (violation :invalid-id "Candidate id must be a positive integer.")))
          (unless (member (candidate-source candidate) +sources+)
            (list (violation :invalid-source "Candidate source is unsupported.")))
          (unless (member (candidate-intent candidate) +intents+)
            (list (violation :invalid-intent "Candidate intent is unsupported.")))
          (unless (stringp (candidate-payload candidate))
            (list (violation :invalid-payload "R1 textual payload must be a string.")))))
(defun candidate-semantic-violations (candidate canonical)
  (append
   (when (and (member (candidate-intent candidate) '(:memory-read :memory-write))
              (null (canonical-memory-ref canonical)))
     (list (violation :missing-memory-reference "Memory intent requires a MemoryRef.")))
   (let ((parent (getf (candidate-metadata candidate) :causal-parent)))
     (when (and parent (not (find parent (canonical-history canonical) :key #'event-id)))
       (list (violation :missing-history-reference "Causal parent is not committed."))))))
(defun candidate-invariant-violations (candidate canonical)
  (append
   (when (find (candidate-id candidate) (canonical-history canonical)
               :key (lambda (event) (getf (event-metadata event) :candidate-id)))
     (list (invariant :identity :duplicate-id nil)))
   (when (and (getf (candidate-metadata candidate) :expected-clock)
              (/= (getf (candidate-metadata candidate) :expected-clock) (canonical-clock canonical)))
     (list (invariant :clock :monotonic-violation t)))))
(defun assistant-payloads (canonical)
  (loop for event in (canonical-history canonical)
        when (eq (event-source event) :assistant) collect (event-payload event)))
(defun observation-check (candidate canonical config)
  (let* ((payload (candidate-payload candidate))
         (threshold (or (getf config :observation-threshold) 1.0))
         (assistant (assistant-payloads canonical))
         (last-two (last assistant 2))
         (result nil))
    (when (and assistant (string= payload (car (last assistant))))
      (push (observation :echo 1.0 threshold :retry) result))
    (when (and (= (length last-two) 2) (apply #'string= last-two))
      (push (observation :stagnation 1.0 threshold :retry-penalty) result))
    (when (getf (candidate-metadata candidate) :discontinuity)
      (push (observation :discontinuity 1.0 threshold :abort) result))
    (nreverse result)))
(defun validate (candidate canonical &optional (config (canonical-config canonical)))
  "Pure fact collection; this function neither selects an action nor changes state."
  (%make-validation-report :candidate-id (candidate-id candidate)
                           :syntax-violations (candidate-syntax-violations candidate)
                           :semantic-violations (candidate-semantic-violations candidate canonical)
                           :invariant-violations (candidate-invariant-violations candidate canonical)
                           :observations (observation-check candidate canonical config)))
(defun recommendation-priority (recommendation)
  (ecase recommendation (:retry 1) (:retry-penalty 2) (:abort 3)))
(defun policy-router (report &optional config)
  (declare (ignore config))
  (cond ((validation-report-syntax-violations report) :reject)
        ((validation-report-semantic-violations report) :reject)
        ((find nil (validation-report-invariant-violations report) :key (lambda (x) (getf x :recoverable))) :reject)
        ((validation-report-invariant-violations report) :defer)
        (t (let ((triggered (remove-if (lambda (x) (< (getf x :score) (getf x :threshold)))
                                        (validation-report-observations report))))
             (if triggered
                 (getf (reduce (lambda (a b) (if (> (recommendation-priority (getf a :recommendation))
                                                       (recommendation-priority (getf b :recommendation))) a b))
                               triggered)
                       :recommendation)
                 :accept)))))

;;; This is the single authoritative mutation boundary.  It returns a new
;;; Canonical value only after every replacement component has been constructed.
(defun commit (event canonical)
  (unless (and (event-p event) (member (event-source event) +sources+)
               (stringp (event-payload event)) (= (event-id event) (next-event-id canonical)))
    (error "Invalid event for commit; Canonical is unchanged."))
  (let* ((clock (1+ (canonical-clock canonical)))
         (metadata (append (plist-copy (event-metadata event)) (list :lamport clock)))
         (committed (make-event (event-id event) (event-source event) (event-payload event) metadata))
         (memory (if (member (getf metadata :intent) '(:memory-write :recover))
                     (append (plist-copy (canonical-memory-ref canonical)) (list :version clock))
                     (plist-copy (canonical-memory-ref canonical)))))
    (values (make-canonical :history (append (canonical-history canonical) (list committed))
                            :config (plist-copy (canonical-config canonical))
                            :memory-ref memory :clock clock)
            committed)))
(defun candidate->event (candidate canonical)
  (make-event (next-event-id canonical) (candidate-source candidate) (candidate-payload candidate)
              (append (plist-copy (candidate-metadata candidate))
                      (list :candidate-id (candidate-id candidate)
                            :intent (candidate-intent candidate)))))
(defun clear-working (state) (setf (kernel-state-working state) nil) state)
(defun fault-for (candidate canonical)
  (list :id (format nil "fault-~D-~D" (canonical-clock canonical) (candidate-id candidate))
        :clock (canonical-clock canonical) :origin :validation :cause "abort action"
        :detector :discontinuity :candidate-id (candidate-id candidate) :extensions nil))
(defun kernel-transition (action state &optional (config (canonical-config (kernel-state-canonical state))))
  "Execute an already selected action.  Kernel performs no validation or I/O."
  (declare (ignore config))
  (unless (member action +actions+) (error "Unknown action: ~S" action))
  (let ((candidate (kernel-state-working state)) (canonical (kernel-state-canonical state)))
    (ecase action
      (:accept (unless (candidate-p candidate) (error "Accept requires Working.Candidate."))
               (multiple-value-bind (next event) (commit (candidate->event candidate canonical) canonical)
                 (setf (kernel-state-canonical state) next)
                 (clear-working state)
                 (values state (make-runtime-command :proceed event))))
      (:reject (clear-working state) (values state (make-runtime-command :discard)))
      (:defer (unless (candidate-p candidate) (error "Defer requires Working.Candidate."))
              (setf (kernel-state-deferred-queue state)
                    (append (kernel-state-deferred-queue state) (list candidate)))
              (clear-working state) (values state (make-runtime-command :sleep)))
      (:retry (values state (make-runtime-command :regenerate)))
      (:retry-penalty (setf (kernel-state-working state)
                            (append (list :candidate candidate)
                                    (list :generation-policy (list :temperature-delta 0.2 :top-p-delta -0.1))))
                      (values state (make-runtime-command :regenerate-with-penalty)))
      (:abort (when (candidate-p candidate)
                (setf (kernel-state-faults state) (append (kernel-state-faults state)
                                                          (list (fault-for candidate canonical)))))
              (values state (make-runtime-command :terminate))))))

(defun working-candidate (working)
  (if (candidate-p working) working (getf working :candidate)))
(defun wake-deferred (state)
  "Revalidate after a successful Canonical advance; never wake on time."
  (let ((queue (kernel-state-deferred-queue state)))
    (setf (kernel-state-deferred-queue state) nil)
    (dolist (candidate queue state)
      (let* ((canonical (kernel-state-canonical state))
             (action (policy-router (validate candidate canonical) (canonical-config canonical))))
        (setf (kernel-state-working state) candidate)
        (kernel-transition action state)))))
(defun recover (canonical)
  "Side-effect-free reconstruction of the context needed to prefill a backend."
  (let ((derived (replay canonical)))
    (list :derived derived :memory-ref (plist-copy (canonical-memory-ref canonical))
          :prefill (build-prompt derived (canonical-memory-ref canonical) (canonical-config canonical)))))
(defun branch-worldline (state &optional new-causal-id)
  "Branch metadata becomes authoritative only through the normal Commit path."
(let* ((canonical (kernel-state-canonical state))
         (new-causal-id (or new-causal-id
                            (1+ (loop for event in (canonical-history canonical)
                                      maximize (or (getf (event-metadata event) :causal-id) 0)))))
         (candidate (make-candidate (next-event-id canonical) :system :branch :recover "worldline branch"
                                    nil (list :causal-id new-causal-id))))
    (setf (kernel-state-working state) candidate)
    (kernel-transition :accept state)))

;;; Runtime integration: backend is injected and remains outside the kernel.
(defun runtime-run-candidate (runtime candidate)
  (let* ((state (runtime-state runtime)) (canonical (kernel-state-canonical state))
         (report (validate candidate canonical (canonical-config canonical)))
         (action (policy-router report (canonical-config canonical))))
    (setf (kernel-state-working state) candidate)
    (multiple-value-bind (next-state command) (kernel-transition action state)
      (setf (runtime-state runtime) next-state (runtime-last-command runtime) command)
      (when (eq (runtime-command-kind command) :proceed) (wake-deferred next-state))
      (values runtime report action command))))
(defun runtime-submit (runtime source text &key (intent :append) metadata)
  (let ((candidate (make-candidate (runtime-next-candidate-id runtime) source :ingress intent text nil metadata)))
    (incf (runtime-next-candidate-id runtime))
    (runtime-run-candidate runtime candidate)))
(defun runtime-run-backend (runtime generator)
  "GENERATOR receives the deterministic prompt and returns non-authoritative text."
  (let* ((canonical (kernel-state-canonical (runtime-state runtime)))
         (derived (replay canonical))
         (prompt (build-prompt derived (canonical-memory-ref canonical) (canonical-config canonical)))
         (text (funcall generator prompt)))
    (runtime-submit runtime :assistant text :metadata (list :causal-parent (and (last-event canonical)
                                                                                  (event-id (last-event canonical)))))))
